2021-04-27 16:35:46,895 INFO    MainThread:6077 [wandb_setup.py:_flush():69] setting env: {}
2021-04-27 16:35:46,895 INFO    MainThread:6077 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-27 16:35:46,895 INFO    MainThread:6077 [wandb_init.py:_log_setup():336] Logging user logs to /home/georgenakayama/CS229_DeepCubeA/wandb/run-20210427_163546-cube3_layer2-cube3layer2_random_data_gen/logs/debug.log
2021-04-27 16:35:46,895 INFO    MainThread:6077 [wandb_init.py:_log_setup():337] Logging internal logs to /home/georgenakayama/CS229_DeepCubeA/wandb/run-20210427_163546-cube3_layer2-cube3layer2_random_data_gen/logs/debug-internal.log
2021-04-27 16:35:46,896 INFO    MainThread:6077 [wandb_init.py:init():369] calling init triggers
2021-04-27 16:35:46,896 INFO    MainThread:6077 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {'env': 'cube3_layer2', 'debug': False, 'lr': 0.001, 'lr_d': 0.9999993, 'max_itrs': 1000000, 'batch_size': 1000, 'single_gpu_training': True, 'loss_thresh': 0.2, 'states_per_update': 500000, 'epochs_per_update': 1, 'num_update_procs': 30, 'update_nnet_batch_size': 10000, 'max_update_steps': 1, 'update_method': 'GBFS', 'eps_max': 0, 'num_test': 10000, 'back_max': 30, 'dynamic_back_max': False, 'dynamic_back_max_per': 25, 'fixed_difficulty': False, 'uniform_data_gen': True, 'nnet_name': 'cube3layer2_random_data_gen', 'update_num': 0, 'save_dir': 'saved_models', 'targ_dir': 'saved_models/cube3layer2_random_data_gen//target/', 'curr_dir': 'saved_models/cube3layer2_random_data_gen//current/', 'output_save_loc': 'saved_models/cube3layer2_random_data_gen//output.txt'}
2021-04-27 16:35:46,896 INFO    MainThread:6077 [wandb_init.py:init():418] starting backend
2021-04-27 16:35:46,896 INFO    MainThread:6077 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-27 16:35:46,911 INFO    MainThread:6077 [backend.py:ensure_launched():123] starting backend process...
2021-04-27 16:35:46,926 INFO    MainThread:6077 [backend.py:ensure_launched():128] started backend process with pid: 6102
2021-04-27 16:35:46,929 INFO    MainThread:6077 [wandb_init.py:init():423] backend started and connected
2021-04-27 16:35:46,933 INFO    MainThread:6077 [wandb_init.py:init():465] updated telemetry
2021-04-27 16:35:46,933 INFO    MainThread:6077 [wandb_init.py:init():484] communicating current version
2021-04-27 16:35:47,876 INFO    MainThread:6077 [wandb_init.py:init():489] got version response 
2021-04-27 16:35:47,876 INFO    MainThread:6077 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-27 16:35:48,119 INFO    MainThread:6077 [wandb_init.py:init():522] starting run threads in backend
2021-04-27 16:35:53,127 INFO    MainThread:6077 [wandb_run.py:_console_start():1524] atexit reg
2021-04-27 16:35:53,128 INFO    MainThread:6077 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-27 16:35:53,128 INFO    MainThread:6077 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-27 16:35:53,130 INFO    MainThread:6077 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-27 16:35:53,130 INFO    MainThread:6077 [wandb_init.py:init():546] run started, returning control to user process
2021-04-27 16:43:59,348 INFO    MainThread:6077 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 1
2021-04-27 16:43:59,348 INFO    MainThread:6077 [wandb_run.py:_restore():1466] restore
2021-04-27 16:44:01,536 INFO    MainThread:6077 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1132
  total_bytes: 1132
}

2021-04-27 16:44:01,929 INFO    MainThread:6077 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1132
  total_bytes: 8656
}

2021-04-27 16:44:02,032 INFO    MainThread:6077 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8656
  total_bytes: 8656
}

2021-04-27 16:44:02,134 INFO    MainThread:6077 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8656
  total_bytes: 8656
}

2021-04-27 16:44:02,236 INFO    MainThread:6077 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8656
  total_bytes: 8656
}

2021-04-27 16:44:02,337 INFO    MainThread:6077 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8656
  total_bytes: 8656
}

2021-04-27 16:44:02,440 INFO    MainThread:6077 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8656
  total_bytes: 8656
}

2021-04-27 16:44:03,826 INFO    MainThread:6077 [wandb_run.py:_show_summary():1771] rendering summary
2021-04-27 16:44:03,826 INFO    MainThread:6077 [wandb_run.py:_show_files():1838] logging synced files
